<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  
    public function findAllExcept($user) {
        $qb = $this->createQueryBuilder('\Entity\Users');
        $qb->select('u')
           ->from('\Entity\Users', 'u')
           ->where( 'u != :user')
           ->setParameter('user', $user);
        return $qb->getQuery()->getResult();
    } 
}
